title: Marcella Harris
description: junior data analyst
baseurl: marcellaharr.github.io
theme: jekyll-theme-cayman
extra_css:
  - "https://fonts.googleapis.com/css?family=Playfair+Display:700,900&display=swap"
  - "blog.css"
